// Sample data so the network is not empty on first visit. Replace with real records from the backend.
// The signed-in pandit is always id "me"; sample rows that mention "me" are only added when the
// pandit opts into sample data while creating their profile.

const days = (n) => new Date(Date.now() + n * 86400000).toISOString().slice(0, 10);
const ago = (n) => new Date(Date.now() - n * 86400000).toISOString();

export const SAMPLE_PANDITS = [
  {
    id: 'p1',
    name: 'Acharya Devdutt Mishra',
    nameHi: 'आचार्य देवदत्त मिश्र',
    headline: 'Vedic Karmkandi · Shukla Yajurvedi · 22 yrs',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    phone: '',
    experience: 22,
    languages: ['hi', 'sa', 'bh'],
    specialities: ['karmkand', 'rudra', 'havan', 'grahShanti'],
    ved: 'yajur',
    bio: 'Trained at Sampurnanand Sanskrit Vishwavidyalaya. Leads Rudrabhishek, Maharudra and Navgrah Shanti anushthans with a team of 11 Vedic Brahmins.',
    rating: 4.9,
    reviews: 212,
    worksDone: 1400,
    yajmanCount: 380,
    verified: true,
    hue: 28,
  },
  {
    id: 'p2',
    name: 'Pt. Raghav Shastri',
    nameHi: 'पं. राघव शास्त्री',
    headline: 'Vivah & Sanskar specialist · Jyotish Acharya',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    phone: '',
    experience: 14,
    languages: ['hi', 'sa', 'en'],
    specialities: ['vivah', 'sanskar', 'jyotish'],
    ved: 'rig',
    bio: 'Conducts weddings in the traditional Vedic paddhati with explanation in Hindi and English, so families understand every vow.',
    rating: 4.8,
    reviews: 154,
    worksDone: 620,
    yajmanCount: 240,
    verified: true,
    hue: 345,
  },
  {
    id: 'p3',
    name: 'Pt. Gopal Krishna Tiwari',
    nameHi: 'पं. गोपाल कृष्ण तिवारी',
    headline: 'Shraddh, Pitru Karya & Gaya pind daan',
    city: 'Gaya',
    state: 'Bihar',
    phone: '',
    experience: 30,
    languages: ['hi', 'bh', 'sa'],
    specialities: ['shraddh', 'karmkand'],
    ved: 'sam',
    bio: 'Gayawal tirth purohit family. Keeps vanshavali records for many families and guides pind daan at Vishnupad, Phalgu and Akshayavat.',
    rating: 4.9,
    reviews: 301,
    worksDone: 5200,
    yajmanCount: 1900,
    verified: true,
    hue: 200,
  },
  {
    id: 'p4',
    name: 'Pt. Sudhanshu Joshi',
    nameHi: 'पं. सुधांशु जोशी',
    headline: 'Bhagwat & Ram Katha vachak',
    city: 'Vrindavan',
    state: 'Uttar Pradesh',
    phone: '',
    experience: 11,
    languages: ['hi', 'sa'],
    specialities: ['katha', 'path'],
    ved: 'yajur',
    bio: 'Bhagwat Saptah, Ram Katha and Sundarkand with a bhajan mandali. Available across North India.',
    rating: 4.7,
    reviews: 88,
    worksDone: 310,
    yajmanCount: 150,
    verified: false,
    hue: 140,
  },
  {
    id: 'p5',
    name: 'Pt. Vinayak Kulkarni',
    nameHi: 'पं. विनायक कुलकर्णी',
    headline: 'Griha Pravesh, Vastu Shanti & Satyanarayan',
    city: 'Pune',
    state: 'Maharashtra',
    phone: '',
    experience: 9,
    languages: ['mr', 'hi', 'sa', 'en'],
    specialities: ['vastu', 'karmkand', 'havan'],
    ved: 'rig',
    bio: 'Rigvedi purohit serving families in Pune and Mumbai. Clear sankalp, punctual and well-organised samagri.',
    rating: 4.8,
    reviews: 97,
    worksDone: 450,
    yajmanCount: 210,
    verified: true,
    hue: 260,
  },
  {
    id: 'p6',
    name: 'Pt. Harish Bhatt',
    nameHi: 'पं. हरीश भट्ट',
    headline: 'Mahamrityunjay & Navgrah jaap · Haridwar',
    city: 'Haridwar',
    state: 'Uttarakhand',
    phone: '',
    experience: 17,
    languages: ['hi', 'sa', 'pa'],
    specialities: ['grahShanti', 'path', 'rudra'],
    ved: 'yajur',
    bio: 'Runs a team of jaap karta Brahmins for sava-lakh Mahamrityunjay, Gayatri and Navgrah anushthans at Har ki Pauri.',
    rating: 4.6,
    reviews: 64,
    worksDone: 280,
    yajmanCount: 130,
    verified: false,
    hue: 50,
  },
];

export const SAMPLE_JOBS = [
  {
    id: 'j1',
    postedBy: 'p1',
    ritual: 'rudrabhishek',
    title: 'Laghu Rudra at a new home — need 4 Vedic pandits',
    date: days(9),
    time: '07:00',
    city: 'Varanasi',
    total: 31000,
    needed: 4,
    description: 'Yajman family from Mumbai. Samagri arranged by us. Shukla Yajurvedi Rudri path required.',
    status: 'open',
    applicants: [{ panditId: 'p6', note: 'Can bring 1 more jaap karta.', at: ago(1) }],
    team: [{ panditId: 'p1', role: 'acharya', weight: 2 }],
    createdAt: ago(2),
  },
  {
    id: 'j2',
    postedBy: 'p2',
    ritual: 'vivah',
    title: 'Wedding on Dev Uthani Ekadashi — two pandits overbooked',
    date: days(30),
    time: '19:30',
    city: 'Prayagraj',
    total: 21000,
    needed: 2,
    description: 'I have three weddings the same evening. Looking for an experienced acharya to lead one completely, with a sahayak.',
    status: 'open',
    applicants: [],
    team: [],
    createdAt: ago(1),
  },
  {
    id: 'j3',
    postedBy: 'p5',
    ritual: 'griha',
    title: 'Griha Pravesh + Vastu Shanti, Hinjewadi',
    date: days(5),
    time: '08:30',
    city: 'Pune',
    total: 15000,
    needed: 2,
    description: 'Marathi and Hindi speaking sahayak needed. Havan with Navgrah ahuti.',
    status: 'open',
    applicants: [],
    team: [{ panditId: 'p5', role: 'acharya', weight: 2 }],
    createdAt: ago(3),
  },
  {
    id: 'j4',
    postedBy: 'p6',
    ritual: 'mahamrityunjay',
    title: 'Sava lakh Mahamrityunjay jaap — 5 jaap karta for 7 days',
    date: days(14),
    time: '06:00',
    city: 'Haridwar',
    total: 61000,
    needed: 5,
    description: 'Daily 11 mala per pandit for 7 days, dashansh havan on the last day. Stay and bhojan arranged.',
    status: 'open',
    applicants: [{ panditId: 'p1', note: '', at: ago(1) }],
    team: [{ panditId: 'p6', role: 'acharya', weight: 2 }],
    createdAt: ago(4),
  },
];

/** Rows that involve the current pandit ("me"); added only with sample data turned on. */
export function sampleForMe() {
  return {
    yajmans: [
      {
        id: 'y1',
        name: 'Ramesh Chandra Sharma',
        phone: '9876500011',
        city: 'Varanasi',
        address: 'Assi Ghat, Varanasi',
        gotra: 'kashyap',
        gotraOther: '',
        pravar: '',
        ved: 'yajur',
        shakha: 'Madhyandini',
        kuldevi: 'Maa Vindhyavasini',
        kulPurohit: '',
        nativePlace: 'Mirzapur',
        dob: '1968-03-14',
        rashi: '5',
        family: [
          { id: 'f1', name: 'Sunita Sharma', relation: 'wife', dob: '1972-07-02' },
          { id: 'f2', name: 'Ankit Sharma', relation: 'son', dob: '1996-11-21' },
          { id: 'f3', name: 'Kavya Sharma', relation: 'daughter', dob: '2001-02-09' },
        ],
        ancestors: [
          { id: 'a1', name: 'Shivprasad Sharma', relation: 'father', tithi: '7' },
          { id: 'a2', name: 'Ramnath Sharma', relation: 'grandfather', tithi: '15' },
          { id: 'a3', name: 'Bhagwati Devi', relation: 'grandmother', tithi: '9' },
        ],
        traditions: [
          { key: 'kuldeviDarshan', lastDone: ago(420), note: 'Chaitra Navratri, whole family goes to Vindhyachal' },
          { key: 'satyanarayan', lastDone: ago(20), note: 'Every Purnima at home' },
          { key: 'gayaShraddh', lastDone: '', note: 'Grandfather did it in 1985 for his father' },
          { key: 'mundanKuldevi', lastDone: '', note: '' },
        ],
        history: [
          { id: 'h1', date: ago(20).slice(0, 10), ritual: 'satyanarayan', amount: 2100, note: 'Purnima katha' },
          { id: 'h2', date: ago(200).slice(0, 10), ritual: 'griha', amount: 11000, note: 'New flat, Sigra' },
        ],
        remediesSent: [],
        notes: 'Prefers morning muhurat. Son lives in Bengaluru.',
        tags: ['regular'],
        createdAt: ago(400),
      },
      {
        id: 'y2',
        name: 'Suresh Agrawal',
        phone: '9876500022',
        city: 'Varanasi',
        address: 'Lanka',
        gotra: 'garg',
        gotraOther: '',
        pravar: '',
        ved: '',
        shakha: '',
        kuldevi: 'Maa Lakshmi (Agroha)',
        kulPurohit: '',
        nativePlace: 'Hisar',
        dob: '1980-10-01',
        rashi: '1',
        family: [{ id: 'f4', name: 'Neha Agrawal', relation: 'wife', dob: '' }],
        ancestors: [{ id: 'a4', name: 'Banwarilal Agrawal', relation: 'father', tithi: '11' }],
        traditions: [
          { key: 'navratriJyoti', lastDone: ago(190), note: '' },
          { key: 'gauDaan', lastDone: ago(30), note: 'Gaushala every Amavasya' },
        ],
        history: [{ id: 'h3', date: ago(190).slice(0, 10), ritual: 'havan', amount: 3100, note: 'Navratri havan' }],
        remediesSent: [],
        notes: '',
        tags: [],
        createdAt: ago(250),
      },
      {
        id: 'y3',
        name: 'Pradeep Kumar Pandey',
        phone: '9876500033',
        city: 'Lucknow',
        address: 'Gomti Nagar',
        gotra: 'bharadwaj',
        gotraOther: '',
        pravar: '',
        ved: 'sam',
        shakha: '',
        kuldevi: 'Shri Kaal Bhairav',
        kulPurohit: 'Pt. Gopal Krishna Tiwari (Gaya)',
        nativePlace: 'Ballia',
        dob: '1975-06-18',
        rashi: '9',
        family: [],
        ancestors: [
          { id: 'a5', name: 'Kamla Pandey', relation: 'mother', tithi: '9' },
          { id: 'a6', name: 'Jagdish Pandey', relation: 'father', tithi: '3' },
        ],
        traditions: [
          { key: 'pitruPaksha', lastDone: ago(370), note: 'Tarpan at Ganga' },
          { key: 'rudrabhishekShravan', lastDone: ago(80), note: '' },
          { key: 'narayanBali', lastDone: '', note: 'Done in 2009 for an uncle' },
        ],
        history: [],
        remediesSent: [],
        notes: '',
        tags: [],
        createdAt: ago(90),
      },
    ],
    connections: [
      { id: 'c1', from: 'me', to: 'p1', status: 'accepted', at: ago(60) },
      { id: 'c2', from: 'p3', to: 'me', status: 'accepted', at: ago(40) },
      { id: 'c3', from: 'p4', to: 'me', status: 'pending', at: ago(1) },
      { id: 'c4', from: 'p5', to: 'me', status: 'pending', at: ago(2) },
    ],
    messages: [
      { id: 'm1', from: 'p1', to: 'me', text: 'Pranam! I may need help for a Laghu Rudra next week. Are you free?', at: ago(1) },
    ],
    jobs: [
      {
        id: 'j0',
        postedBy: 'p1',
        ritual: 'navgrah',
        title: 'Navgrah Shanti — Sigra',
        date: days(-12),
        time: '08:00',
        city: 'Varanasi',
        total: 11000,
        needed: 2,
        description: '',
        status: 'paid',
        applicants: [],
        team: [
          { panditId: 'p1', role: 'acharya', weight: 2 },
          { panditId: 'me', role: 'sahayak', weight: 1 },
        ],
        createdAt: ago(30),
        paidAt: ago(10),
      },
    ],
    ledger: [
      { id: 'l1', jobId: 'j0', panditId: 'platform', kind: 'commission', amount: 1100, at: ago(10) },
      { id: 'l2', jobId: 'j0', panditId: 'p1', kind: 'payout', amount: 6600, at: ago(10) },
      { id: 'l3', jobId: 'j0', panditId: 'me', kind: 'payout', amount: 3300, at: ago(10) },
    ],
  };
}
