// Phal (results) of each graha in each of the 12 houses (bhava), counted from the Lagna.
// Based on the classical meanings in Brihat Parashara Hora Shastra and Phaladeepika,
// written as plain guidance. Index 0 = house 1 … index 11 = house 12.
const p = (en, hi) => ({ en, hi });

export const HOUSE_TOPICS = [
  p('self, body, health and personality', 'स्वयं, शरीर, स्वास्थ्य और व्यक्तित्व'),
  p('wealth, family, speech and food', 'धन, कुटुंब, वाणी और भोजन'),
  p('courage, effort, siblings and communication', 'पराक्रम, प्रयास, भाई-बहन और संवाद'),
  p('mother, home, property, vehicles and inner peace', 'माता, घर, भूमि-भवन, वाहन और मन की शांति'),
  p('intelligence, education, children and romance', 'बुद्धि, शिक्षा, संतान और प्रेम'),
  p('enemies, debts, disease, competition and service', 'शत्रु, ऋण, रोग, प्रतियोगिता और नौकरी'),
  p('marriage, spouse and partnerships', 'विवाह, जीवनसाथी और साझेदारी'),
  p('longevity, sudden events, secrets and inheritance', 'आयु, आकस्मिक घटनाएँ, गूढ़ विषय और विरासत'),
  p('luck, dharma, father, guru and long journeys', 'भाग्य, धर्म, पिता, गुरु और लंबी यात्राएँ'),
  p('career, status, karma and reputation', 'करियर, पद-प्रतिष्ठा, कर्म और मान-सम्मान'),
  p('income, gains, friends and wishes', 'आय, लाभ, मित्र और इच्छापूर्ति'),
  p('expenses, foreign lands, sleep and moksha', 'व्यय, विदेश, नींद और मोक्ष'),
];

export const HOUSE_PHAL = {
  sun: [
    p('Confident, dignified and born to lead. You command respect and may get favour from government or seniors. Guard against ego, and take care of eyes, head and blood pressure.', 'आत्मविश्वासी, तेजस्वी और नेतृत्व करने वाले। आपको सम्मान मिलता है और सरकार या वरिष्ठों से सहयोग मिल सकता है। अहंकार से बचें तथा आँख, सिर और रक्तचाप का ध्यान रखें।'),
    p('Earnings through government, authority or father’s support. Speech can sound harsh, which may create tension in the family; soft words will bring more wealth.', 'सरकार, अधिकार या पिता के सहयोग से धन लाभ। वाणी कठोर हो सकती है जिससे परिवार में तनाव हो; मधुर वाणी से धन बढ़ेगा।'),
    p('Strong courage and willpower; success comes through your own effort. Good for leadership in media, writing or sports. Ego clashes with siblings are possible.', 'प्रबल साहस और इच्छाशक्ति; सफलता अपने प्रयास से मिलती है। मीडिया, लेखन या खेल में नेतृत्व के लिए अच्छा। भाई-बहनों से अहं का टकराव संभव।'),
    p('Status and property can come, but domestic peace needs effort. Relations with mother or home life may feel strained; keep the home atmosphere warm.', 'पद और संपत्ति मिल सकती है, पर घरेलू शांति के लिए प्रयास करना होगा। माता या घर के वातावरण में खिंचाव हो सकता है; घर का माहौल स्नेहपूर्ण रखें।'),
    p('Sharp, authoritative intelligence with interest in politics, administration or teaching. Children may be few or need extra care; avoid speculation driven by pride.', 'तेज़ और प्रभावशाली बुद्धि; राजनीति, प्रशासन या अध्यापन में रुचि। संतान कम हो सकती है या अधिक देखभाल चाहिए; अहंकारवश सट्टे से बचें।'),
    p('An excellent placement. You defeat rivals, win competitions and do well in government service, medicine or law. Health and stamina are generally good.', 'उत्तम स्थिति। शत्रुओं पर विजय, प्रतियोगिता में सफलता और सरकारी सेवा, चिकित्सा या कानून में अच्छा प्रदर्शन। स्वास्थ्य और ऊर्जा सामान्यतः अच्छी।'),
    p('Spouse is strong-willed and self-respecting. Ego clashes in marriage or partnership are likely, so practise humility; marriage may be slightly delayed.', 'जीवनसाथी दृढ़ इच्छाशक्ति वाला और स्वाभिमानी। विवाह या साझेदारी में अहं का टकराव संभव, इसलिए विनम्र रहें; विवाह में थोड़ी देरी हो सकती है।'),
    p('Health may go up and down, especially eyes, heart and heat-related issues. Interest in research and hidden subjects; inheritance may come with hurdles.', 'स्वास्थ्य में उतार-चढ़ाव, विशेषकर आँख, हृदय और गर्मी संबंधी। शोध और गूढ़ विषयों में रुचि; विरासत में बाधाएँ आ सकती हैं।'),
    p('Fortunate and principled, with faith in dharma. You respect your father, though opinions may differ. Good for higher studies, law and pilgrimages.', 'भाग्यशाली और सिद्धांतवादी, धर्म में आस्था। पिता का सम्मान करते हैं, यद्यपि विचार भिन्न हो सकते हैं। उच्च शिक्षा, कानून और तीर्थ यात्रा के लिए शुभ।'),
    p('One of the best placements (Sun gets directional strength here). Fame, authority and a high position in career, especially government, administration or management.', 'सर्वश्रेष्ठ स्थितियों में से एक (यहाँ सूर्य को दिग्बल मिलता है)। करियर में यश, अधिकार और उच्च पद, विशेषकर सरकार, प्रशासन या प्रबंधन में।'),
    p('High income and influential friends. Wishes are fulfilled through powerful contacts; elder siblings or seniors help you rise.', 'अच्छी आय और प्रभावशाली मित्र। प्रभावशाली संपर्कों से इच्छाएँ पूरी होती हैं; बड़े भाई-बहन या वरिष्ठ उन्नति में सहायक।'),
    p('Expenses run high and you may live or work away from home or abroad. Watch eyesight and sleep. Spiritual interests grow with age.', 'खर्च अधिक रहते हैं और घर से दूर या विदेश में रहना/काम करना संभव। आँखों और नींद का ध्यान रखें। आयु के साथ आध्यात्मिक रुचि बढ़ती है।'),
  ],
  moon: [
    p('Attractive, gentle and emotionally sensitive. You are popular and caring, but moods can change quickly; a calm routine keeps you balanced.', 'आकर्षक, कोमल और भावुक। आप लोकप्रिय और देखभाल करने वाले हैं, पर मनोदशा जल्दी बदल सकती है; शांत दिनचर्या संतुलन बनाए रखती है।'),
    p('Sweet speech and love for family. Wealth comes but fluctuates like the Moon; saving regularly is important. Fond of good food.', 'मधुर वाणी और परिवार से प्रेम। धन आता है पर चंद्रमा की तरह घटता-बढ़ता है; नियमित बचत आवश्यक। अच्छे भोजन के शौकीन।'),
    p('Creative and fond of travel, writing and communication. Siblings are supportive, but the mind can be restless; short trips refresh you.', 'रचनात्मक; यात्रा, लेखन और संवाद में रुचि। भाई-बहन सहयोगी, पर मन चंचल रह सकता है; छोटी यात्राएँ ताज़गी देती हैं।'),
    p('A very good placement (Moon gets directional strength here). Mother’s love, a happy home, property and vehicles. Inner peace is strong.', 'बहुत शुभ स्थिति (यहाँ चंद्रमा को दिग्बल मिलता है)। माता का स्नेह, सुखी घर, संपत्ति और वाहन। मन में शांति रहती है।'),
    p('Imaginative and intelligent, with joy from children and romance. Good for arts, teaching and anything that needs feeling and intuition.', 'कल्पनाशील और बुद्धिमान; संतान और प्रेम से सुख। कला, अध्यापन और भावना व अंतर्ज्ञान से जुड़े कार्यों के लिए अच्छा।'),
    p('The mind can carry stress and worry; take care of digestion and emotional health. You serve others well and may work in healthcare or service.', 'मन में तनाव और चिंता रह सकती है; पाचन और भावनात्मक स्वास्थ्य का ध्यान रखें। आप सेवाभावी हैं और स्वास्थ्य या सेवा क्षेत्र में कार्य कर सकते हैं।'),
    p('A caring, attractive spouse and good public dealings. Success in business and work that involves people; emotional needs in marriage are high.', 'देखभाल करने वाला, आकर्षक जीवनसाथी और जनसंपर्क में सफलता। लोगों से जुड़े व्यवसाय में सफलता; विवाह में भावनात्मक अपेक्षाएँ अधिक।'),
    p('Emotional ups and downs and strong intuition, with interest in mysticism. Be careful around water and with mental stress; meditation helps greatly.', 'भावनात्मक उतार-चढ़ाव और प्रबल अंतर्ज्ञान; रहस्यमय विषयों में रुचि। जल और मानसिक तनाव के प्रति सावधान रहें; ध्यान बहुत लाभ देता है।'),
    p('Fortunate and devotional, with love for pilgrimages and travel. Good relations with father and teachers; fortune rises through kindness.', 'भाग्यशाली और भक्तिभाव वाले; तीर्थ और यात्रा से प्रेम। पिता व गुरुजनों से अच्छे संबंध; दयालुता से भाग्य बढ़ता है।'),
    p('A public-facing career that brings popularity. Work related to people, food, hospitality, travel or healthcare suits you; job changes are possible.', 'जनता से जुड़ा करियर जो लोकप्रियता देता है। लोगों, भोजन, आतिथ्य, यात्रा या स्वास्थ्य से जुड़ा कार्य उपयुक्त; नौकरी में बदलाव संभव।'),
    p('Good income, many friends and gains through women or the public. Most wishes are fulfilled.', 'अच्छी आय, अनेक मित्र और स्त्रियों या जनता से लाभ। अधिकांश इच्छाएँ पूरी होती हैं।'),
    p('Expenses, disturbed sleep or living far from the birthplace are possible. Strong imagination and spiritual inclination; foreign connections.', 'खर्च, नींद में बाधा या जन्मस्थान से दूर रहना संभव। प्रबल कल्पनाशक्ति और आध्यात्मिक झुकाव; विदेश से संबंध।'),
  ],
  mars: [
    p('Energetic, brave and quick to act. Prone to anger, impatience and minor injuries to the head. This causes Manglik dosha; channel energy into sport or exercise.', 'ऊर्जावान, साहसी और तुरंत कार्य करने वाले। क्रोध, अधीरता और सिर में चोट की आशंका। इससे मांगलिक दोष बनता है; ऊर्जा को खेल या व्यायाम में लगाएँ।'),
    p('Speech can be sharp and family disputes may arise. Earnings from land, engineering or technical work. Mild Manglik effect; speak calmly.', 'वाणी तीखी हो सकती है और पारिवारिक विवाद संभव। भूमि, इंजीनियरिंग या तकनीकी कार्य से आय। हल्का मांगलिक प्रभाव; शांति से बोलें।'),
    p('A strong placement: great courage, initiative and success through effort. Good for sports, defence and competitive fields. Siblings may be dominant.', 'बलवान स्थिति: अदम्य साहस, पहल और प्रयास से सफलता। खेल, रक्षा और प्रतिस्पर्धी क्षेत्रों के लिए अच्छा। भाई-बहन प्रभावशाली हो सकते हैं।'),
    p('Gains from land and property, but restlessness or quarrels at home are possible. Causes Manglik dosha; take care of mother’s health.', 'भूमि-भवन से लाभ, पर घर में अशांति या कलह संभव। इससे मांगलिक दोष बनता है; माता के स्वास्थ्य का ध्यान रखें।'),
    p('Sharp, competitive mind, good for engineering, sports and strategy. Children may be energetic; avoid risky speculation.', 'तीक्ष्ण, प्रतिस्पर्धी बुद्धि; इंजीनियरिंग, खेल और रणनीति के लिए अच्छा। संतान ऊर्जावान; जोखिम भरे सट्टे से बचें।'),
    p('An excellent placement. Victory over enemies, success in competitions, police, army, surgery or sports. Strong immunity and fighting spirit.', 'उत्तम स्थिति। शत्रुओं पर विजय, प्रतियोगिता, पुलिस, सेना, सर्जरी या खेल में सफलता। मज़बूत रोग-प्रतिरोधक क्षमता और संघर्ष-शक्ति।'),
    p('Causes Manglik dosha. A passionate but argumentative married life; patience and matching with a suitable partner are important. Partnerships need clear terms.', 'इससे मांगलिक दोष बनता है। जोशपूर्ण पर विवादप्रवण वैवाहिक जीवन; धैर्य और उपयुक्त जीवनसाथी से मिलान महत्वपूर्ण। साझेदारी में शर्तें स्पष्ट रखें।'),
    p('Causes Manglik dosha. Risk of accidents, surgery or sudden events; drive carefully. Good for research, investigation and occult studies.', 'इससे मांगलिक दोष बनता है। दुर्घटना, शल्य-चिकित्सा या आकस्मिक घटनाओं का भय; वाहन सावधानी से चलाएँ। शोध, जाँच और गूढ़ विद्या के लिए अच्छा।'),
    p('Fortune comes through bold effort. Differences with father or teachers are possible; you fight for your beliefs.', 'साहसिक प्रयास से भाग्योदय। पिता या गुरुजनों से मतभेद संभव; आप अपने विश्वासों के लिए संघर्ष करते हैं।'),
    p('A very strong career placement (Mars gets directional strength here). Success in engineering, defence, police, administration, real estate or surgery.', 'करियर के लिए बहुत बलवान स्थिति (यहाँ मंगल को दिग्बल मिलता है)। इंजीनियरिंग, रक्षा, पुलिस, प्रशासन, रियल एस्टेट या सर्जरी में सफलता।'),
    p('Good income through land, technical work or elder siblings. Ambitions are achieved with drive.', 'भूमि, तकनीकी कार्य या बड़े भाई-बहनों से अच्छी आय। लगन से महत्वाकांक्षाएँ पूरी होती हैं।'),
    p('Causes Manglik dosha. Expenses, hidden enemies and disturbed sleep are possible. Energy is best used in service, sport or spiritual discipline.', 'इससे मांगलिक दोष बनता है। खर्च, गुप्त शत्रु और नींद में बाधा संभव। ऊर्जा का सबसे अच्छा उपयोग सेवा, खेल या आध्यात्मिक साधना में है।'),
  ],
  mercury: [
    p('Intelligent, witty, youthful and an excellent communicator. Good at business, learning and adapting to people.', 'बुद्धिमान, हाज़िरजवाब, युवा दिखने वाले और उत्कृष्ट वक्ता। व्यापार, सीखने और लोगों के साथ तालमेल में कुशल।'),
    p('Eloquent speech and wealth through trade, teaching, accounts or writing. Good with numbers and languages.', 'प्रभावशाली वाणी; व्यापार, अध्यापन, लेखा या लेखन से धन। अंकों और भाषाओं में दक्ष।'),
    p('Skilled in writing, media, marketing and communication. Many short trips and good relations with siblings.', 'लेखन, मीडिया, मार्केटिंग और संवाद में कुशल। अनेक छोटी यात्राएँ और भाई-बहनों से अच्छे संबंध।'),
    p('Good education and a peaceful, cultured home. Gains from property and vehicles; you keep learning throughout life.', 'अच्छी शिक्षा और शांत, सुसंस्कृत घर। भूमि और वाहन से लाभ; जीवनभर सीखते रहते हैं।'),
    p('Sharp intellect and success in studies, exams and analytical fields. Children are intelligent.', 'तेज़ बुद्धि; पढ़ाई, परीक्षा और विश्लेषणात्मक क्षेत्रों में सफलता। संतान बुद्धिमान।'),
    p('Analytical and good at service, law, accounts and audit. Overthinking and nervous stress are possible; keep the mind relaxed.', 'विश्लेषक; नौकरी, कानून, लेखा और ऑडिट में अच्छे। अधिक सोचने और नसों के तनाव की आशंका; मन को शांत रखें।'),
    p('Success in business partnerships. The spouse is youthful, intelligent and talkative.', 'व्यापारिक साझेदारी में सफलता। जीवनसाथी युवा, बुद्धिमान और बातूनी।'),
    p('Interest in research, astrology and hidden knowledge. Long life, and gains through insurance or inheritance.', 'शोध, ज्योतिष और गूढ़ ज्ञान में रुचि। दीर्घायु, और बीमा या विरासत से लाभ।'),
    p('Higher learning, good teachers and a logical approach to religion. Good for publishing, law and teaching.', 'उच्च शिक्षा, अच्छे गुरु और धर्म के प्रति तार्किक दृष्टि। प्रकाशन, कानून और अध्यापन के लिए अच्छा।'),
    p('Career in business, communication, accounts, IT, media or consulting. Multiple skills bring success.', 'व्यापार, संवाद, लेखा, आईटी, मीडिया या परामर्श में करियर। अनेक कौशल सफलता दिलाते हैं।'),
    p('Gains through trade, networking and intelligent friends. Multiple sources of income are possible.', 'व्यापार, नेटवर्क और बुद्धिमान मित्रों से लाभ। आय के कई स्रोत संभव।'),
    p('Expenses on learning or travel and foreign links. Overthinking can disturb sleep; journaling helps.', 'शिक्षा या यात्रा पर खर्च और विदेश से संबंध। अधिक सोचने से नींद प्रभावित हो सकती है; डायरी लिखना लाभदायक।'),
  ],
  jupiter: [
    p('Wise, respected, optimistic and blessed (Jupiter gets directional strength here). Good health and a protective grace over life; weight gain is possible.', 'ज्ञानी, सम्मानित, आशावादी और भाग्यशाली (यहाँ गुरु को दिग्बल मिलता है)। अच्छा स्वास्थ्य और जीवन पर दैवी कृपा; वज़न बढ़ने की संभावना।'),
    p('Wealth, a truthful and sweet voice, and family harmony. Good for teaching, finance and advisory work.', 'धन, सत्य और मधुर वाणी तथा पारिवारिक सौहार्द। अध्यापन, वित्त और परामर्श कार्य के लिए अच्छा।'),
    p('Success comes through steady effort. Good for writing and scholarly work; relations with siblings are polite but limited.', 'निरंतर प्रयास से सफलता। लेखन और विद्वत्तापूर्ण कार्य के लिए अच्छा; भाई-बहनों से संबंध शालीन पर सीमित।'),
    p('Happiness at home, a good mother, property, vehicles and fine education. Inner contentment.', 'घर में सुख, माता का आशीर्वाद, संपत्ति, वाहन और उत्तम शिक्षा। मन में संतोष।'),
    p('An excellent placement. Wisdom, good children, success in education and strong devotion. Mantras give quick results.', 'उत्तम स्थिति। बुद्धिमत्ता, सुयोग्य संतान, शिक्षा में सफलता और प्रबल भक्ति। मंत्र शीघ्र फल देते हैं।'),
    p('You overcome debts and enemies through fairness. Watch weight, liver and sugar levels. Good for service and counselling.', 'न्यायप्रियता से ऋण और शत्रुओं पर विजय। वज़न, लिवर और शुगर का ध्यान रखें। नौकरी और परामर्श के लिए अच्छा।'),
    p('A wise, cultured and supportive spouse and a respected marriage. Good for partnerships and public dealings.', 'ज्ञानी, सुसंस्कृत और सहयोगी जीवनसाथी तथा सम्मानित वैवाहिक जीवन। साझेदारी और जनसंपर्क के लिए अच्छा।'),
    p('Long life and interest in spirituality and occult studies. Inheritance or gains through the spouse’s family are possible.', 'दीर्घायु और अध्यात्म व गूढ़ विद्या में रुचि। विरासत या ससुराल पक्ष से लाभ संभव।'),
    p('Very fortunate. Blessings of guru and father, strong dharma, higher learning and pilgrimages.', 'अत्यंत भाग्यशाली। गुरु और पिता का आशीर्वाद, धर्म में दृढ़ता, उच्च शिक्षा और तीर्थ यात्राएँ।'),
    p('A respected career in teaching, law, finance, advisory or religious work. Ethical conduct brings status.', 'अध्यापन, कानून, वित्त, परामर्श या धार्मिक कार्य में सम्मानित करियर। नैतिक आचरण से प्रतिष्ठा मिलती है।'),
    p('Large gains, wise friends and fulfilment of wishes. Elders and mentors support you.', 'बड़ा लाभ, ज्ञानी मित्र और इच्छापूर्ति। बड़े-बुज़ुर्ग और मार्गदर्शक सहायता करते हैं।'),
    p('Spending on charity and good causes, foreign travel and deep spiritual growth. A placement that favours moksha.', 'दान और शुभ कार्यों पर खर्च, विदेश यात्रा और गहरी आध्यात्मिक उन्नति। मोक्ष के लिए अनुकूल स्थिति।'),
  ],
  venus: [
    p('Attractive, charming and artistic, with a love of beauty and comfort. Popular in social circles.', 'आकर्षक, मनमोहक और कलाप्रेमी; सौंदर्य और सुख-सुविधा से प्रेम। सामाजिक रूप से लोकप्रिय।'),
    p('Wealth, sweet speech, good food and a happy family. Earnings from arts, beauty or luxury goods.', 'धन, मधुर वाणी, अच्छा भोजन और सुखी परिवार। कला, सौंदर्य या विलासिता की वस्तुओं से आय।'),
    p('Creative talent in music, design or media and an enjoyable social life. Good relations with siblings.', 'संगीत, डिज़ाइन या मीडिया में रचनात्मक प्रतिभा और आनंदमय सामाजिक जीवन। भाई-बहनों से अच्छे संबंध।'),
    p('A beautiful home, vehicles and comforts (Venus gets directional strength here). Happiness from mother and property.', 'सुंदर घर, वाहन और सुख-सुविधाएँ (यहाँ शुक्र को दिग्बल मिलता है)। माता और संपत्ति से सुख।'),
    p('Romance, artistic intelligence and joy from children. Good for creative studies and entertainment.', 'प्रेम, कलात्मक बुद्धि और संतान से सुख। रचनात्मक शिक्षा और मनोरंजन के लिए अच्छा।'),
    p('Ups and downs in relationships; watch sugar, kidneys and indulgence. Work in fashion, hospitality or healthcare suits you.', 'संबंधों में उतार-चढ़ाव; शुगर, किडनी और अति-भोग से सावधान। फैशन, आतिथ्य या स्वास्थ्य क्षेत्र में कार्य उपयुक्त।'),
    p('An attractive, loving spouse and a romantic married life. Good for business partnerships; avoid over-indulgence.', 'आकर्षक, प्रेमपूर्ण जीवनसाथी और रोमांटिक वैवाहिक जीवन। व्यापारिक साझेदारी के लिए अच्छा; अति-भोग से बचें।'),
    p('Gains through the spouse or inheritance and sudden wealth. Keep relationships transparent.', 'जीवनसाथी या विरासत से लाभ और आकस्मिक धन। संबंधों में पारदर्शिता रखें।'),
    p('Fortunate, with wealth, comforts and pleasant travel. Devotion to the Divine Mother brings blessings.', 'भाग्यशाली; धन, सुख-सुविधा और सुखद यात्राएँ। देवी माँ की भक्ति से आशीर्वाद मिलता है।'),
    p('A career in arts, media, fashion, beauty, hospitality, finance or luxury brands. Charm helps you rise.', 'कला, मीडिया, फैशन, सौंदर्य, आतिथ्य, वित्त या लक्ज़री ब्रांड में करियर। आकर्षण से उन्नति।'),
    p('Good gains, influential friends and a life of comfort. Wishes related to luxury are fulfilled.', 'अच्छा लाभ, प्रभावशाली मित्र और सुखमय जीवन। सुख-सुविधा संबंधी इच्छाएँ पूरी होती हैं।'),
    p('Spending on comforts and travel; foreign connections. Classically a good placement for pleasures of life.', 'सुख-सुविधा और यात्रा पर खर्च; विदेश से संबंध। शास्त्रानुसार जीवन के सुखों के लिए अच्छी स्थिति।'),
  ],
  saturn: [
    p('Serious, disciplined and hardworking. Early life may bring delays, but you mature into steady success. Take care of bones, joints and energy levels.', 'गंभीर, अनुशासित और परिश्रमी। आरंभिक जीवन में देरी हो सकती है, पर धीरे-धीरे स्थायी सफलता मिलती है। हड्डियों, जोड़ों और ऊर्जा का ध्यान रखें।'),
    p('Wealth builds slowly through patience. Speech is measured or blunt; family duties weigh on you.', 'धैर्य से धन धीरे-धीरे बढ़ता है। वाणी संयमित या रूखी; पारिवारिक ज़िम्मेदारियाँ अधिक।'),
    p('Persistent courage and long-term effort bring success. Good for technical skills; relations with siblings may be formal.', 'दृढ़ साहस और दीर्घकालीन प्रयास से सफलता। तकनीकी कौशल के लिए अच्छा; भाई-बहनों से संबंध औपचारिक हो सकते हैं।'),
    p('Domestic peace needs effort; old property or ancestral home matters. Take care of mother’s health.', 'घरेलू शांति के लिए प्रयास आवश्यक; पुरानी या पैतृक संपत्ति से जुड़े विषय। माता के स्वास्थ्य का ध्यान रखें।'),
    p('Delays in education or children are possible, and the mind is serious. Success comes through disciplined study.', 'शिक्षा या संतान में देरी संभव और मन गंभीर रहता है। अनुशासित अध्ययन से सफलता।'),
    p('An excellent placement. You defeat enemies, succeed in service and competition, and handle long-term work well.', 'उत्तम स्थिति। शत्रुओं पर विजय, नौकरी और प्रतियोगिता में सफलता तथा दीर्घकालीन कार्य में कुशलता।'),
    p('Marriage may be delayed or the spouse may be mature and responsible (Saturn gets directional strength here). Stable once settled.', 'विवाह में देरी संभव या जीवनसाथी परिपक्व और ज़िम्मेदार (यहाँ शनि को दिग्बल मिलता है)। एक बार स्थिर होने पर संबंध टिकाऊ।'),
    p('Long life, but chronic health matters and hard lessons are possible. Good for research and serious study.', 'दीर्घायु, पर पुराने रोग और कठिन अनुभव संभव। शोध और गंभीर अध्ययन के लिए अच्छा।'),
    p('Faith comes through experience; differences with father are possible. Fortune rises later in life.', 'अनुभव से आस्था आती है; पिता से मतभेद संभव। भाग्योदय जीवन में देर से।'),
    p('Hard-earned career success, authority and a steady rise. Good for administration, law, engineering or large organisations.', 'मेहनत से अर्जित करियर सफलता, अधिकार और स्थिर उन्नति। प्रशासन, कानून, इंजीनियरिंग या बड़े संगठनों के लिए अच्छा।'),
    p('Steady and growing gains with time. Older or long-standing friends help; late but solid success.', 'समय के साथ स्थिर और बढ़ता लाभ। पुराने मित्र सहायक; देर से पर ठोस सफलता।'),
    p('Expenses, solitude or life away from home or abroad. Spiritual detachment and service bring peace.', 'खर्च, एकांत या घर से दूर/विदेश में जीवन। आध्यात्मिक वैराग्य और सेवा से शांति।'),
  ],
  rahu: [
    p('Unconventional, ambitious and magnetic, with confusion about identity at times. Take care of health and avoid shortcuts.', 'अपरंपरागत, महत्वाकांक्षी और आकर्षक; कभी-कभी पहचान को लेकर भ्रम। स्वास्थ्य का ध्यान रखें और शॉर्टकट से बचें।'),
    p('Wealth through unusual or foreign sources. Speech may be harsh or unclear; family tensions possible; watch eating habits.', 'असामान्य या विदेशी स्रोतों से धन। वाणी कठोर या अस्पष्ट हो सकती है; पारिवारिक तनाव संभव; खान-पान का ध्यान रखें।'),
    p('A very good placement. Great courage, success in media, technology and marketing. You take bold risks that pay off.', 'बहुत अच्छी स्थिति। अदम्य साहस, मीडिया, तकनीक और मार्केटिंग में सफलता। साहसिक जोखिम लाभ देते हैं।'),
    p('A restless home life and frequent changes of residence; possible settlement abroad. Keep mother close.', 'घर में बेचैनी और बार-बार निवास परिवर्तन; विदेश में बसने की संभावना। माता से जुड़े रहें।'),
    p('Unusual, inventive thinking. Avoid speculation and gambling; children’s matters need patience.', 'असामान्य, आविष्कारशील सोच। सट्टे और जुए से बचें; संतान संबंधी विषयों में धैर्य रखें।'),
    p('An excellent placement. You overcome enemies, debts and disease and succeed in competitions.', 'उत्तम स्थिति। शत्रु, ऋण और रोग पर विजय तथा प्रतियोगिता में सफलता।'),
    p('An unconventional marriage or partner from a different background. Misunderstandings in partnership are possible; be transparent.', 'अपरंपरागत विवाह या भिन्न पृष्ठभूमि का जीवनसाथी। साझेदारी में गलतफहमी संभव; पारदर्शिता रखें।'),
    p('Sudden events, interest in occult and research. Take care of health and avoid risky ventures.', 'आकस्मिक घटनाएँ, गूढ़ विद्या और शोध में रुचि। स्वास्थ्य का ध्यान रखें और जोखिम भरे कार्यों से बचें।'),
    p('Unconventional beliefs and foreign travel. Differences with father or teachers; question traditions wisely.', 'अपरंपरागत विश्वास और विदेश यात्रा। पिता या गुरुजनों से मतभेद; परंपराओं पर विवेक से प्रश्न करें।'),
    p('An ambitious career with sudden rise, especially in politics, technology, media or foreign companies.', 'महत्वाकांक्षी करियर और अचानक उन्नति, विशेषकर राजनीति, तकनीक, मीडिया या विदेशी कंपनियों में।'),
    p('Large gains, a big network and fulfilment of desires. One of the best placements of Rahu.', 'बड़ा लाभ, विस्तृत नेटवर्क और इच्छापूर्ति। राहु की सर्वश्रेष्ठ स्थितियों में से एक।'),
    p('Foreign lands, high expenses and disturbed sleep are possible. Spiritual seeking eventually brings peace.', 'विदेश, अधिक खर्च और नींद में बाधा संभव। आध्यात्मिक खोज अंततः शांति देती है।'),
  ],
  ketu: [
    p('Spiritual, introverted and mysterious. Health may fluctuate; you are intuitive and detached from show.', 'आध्यात्मिक, अंतर्मुखी और रहस्यमय। स्वास्थ्य में उतार-चढ़ाव; आप अंतर्ज्ञानी और दिखावे से दूर रहते हैं।'),
    p('Detachment from family or wealth, and speech that is blunt or minimal. Pay attention to diet and teeth.', 'परिवार या धन से विरक्ति; वाणी रूखी या कम। आहार और दाँतों का ध्यान रखें।'),
    p('Courage and spiritual strength; a good placement for Ketu. Success through effort without much show.', 'साहस और आध्यात्मिक बल; केतु के लिए अच्छी स्थिति। बिना दिखावे के प्रयास से सफलता।'),
    p('Detachment from home comforts and possible changes of residence. Take care of mother’s health.', 'घरेलू सुखों से विरक्ति और निवास परिवर्तन संभव। माता के स्वास्थ्य का ध्यान रखें।'),
    p('Intuitive and spiritual intelligence; interest in mantra and astrology. Children’s matters need care.', 'अंतर्ज्ञानी और आध्यात्मिक बुद्धि; मंत्र और ज्योतिष में रुचि। संतान संबंधी विषयों में सावधानी।'),
    p('An excellent placement. Victory over enemies and disease, and healing abilities.', 'उत्तम स्थिति। शत्रु और रोग पर विजय तथा उपचार की क्षमता।'),
    p('A sense of detachment in marriage; the partner may be spiritual or distant at times. Give time to the relationship.', 'विवाह में विरक्ति का भाव; जीवनसाथी आध्यात्मिक या कभी-कभी दूर। संबंध को समय दें।'),
    p('Deep interest in occult and research, sudden events and spiritual transformation.', 'गूढ़ विद्या और शोध में गहरी रुचि, आकस्मिक घटनाएँ और आध्यात्मिक परिवर्तन।'),
    p('Spiritual and unorthodox, with pilgrimages. Your own experience matters more than rituals.', 'आध्यात्मिक और अपरंपरागत; तीर्थ यात्राएँ। अनुष्ठानों से अधिक अपना अनुभव महत्वपूर्ण।'),
    p('Career changes or work in technical, research, healing or spiritual fields. Success comes without craving it.', 'करियर में बदलाव या तकनीकी, शोध, उपचार या आध्यात्मिक क्षेत्र में कार्य। बिना लालसा के सफलता।'),
    p('Gains and spiritual friendships; desires are fulfilled but bring little attachment.', 'लाभ और आध्यात्मिक मित्रता; इच्छाएँ पूरी होती हैं पर आसक्ति कम रहती है।'),
    p('A strong placement for moksha and spiritual liberation; foreign links and expenses on spiritual pursuits.', 'मोक्ष और आध्यात्मिक मुक्ति के लिए प्रबल स्थिति; विदेश से संबंध और आध्यात्मिक कार्यों पर खर्च।'),
  ],
};
