// Lagna phal (personality from the rising sign), Rashi phal (mind from the Moon sign)
// and general Mahadasha results. Index 0 = Aries (Mesha) … 11 = Pisces (Meena).
const p = (en, hi) => ({ en, hi });

export const LAGNA_PHAL = [
  p('Mesha lagna makes you energetic, brave and quick to start new things. You are a natural leader who likes independence, but patience and finishing what you begin are lessons to learn. Mars is your lagna lord.', 'मेष लग्न आपको ऊर्जावान, साहसी और नई शुरुआत करने वाला बनाता है। आप स्वाभाविक नेता हैं और स्वतंत्रता पसंद करते हैं, पर धैर्य और शुरू किया काम पूरा करना सीखना होगा। आपके लग्नेश मंगल हैं।'),
  p('Vrishabha lagna gives a calm, stable and patient nature, with love for beauty, comfort and good food. You are loyal and practical, but can be stubborn. Venus is your lagna lord.', 'वृषभ लग्न शांत, स्थिर और धैर्यवान स्वभाव देता है; सौंदर्य, सुख-सुविधा और अच्छे भोजन से प्रेम। आप वफ़ादार और व्यावहारिक हैं, पर हठी भी हो सकते हैं। आपके लग्नेश शुक्र हैं।'),
  p('Mithuna lagna makes you curious, witty and a good communicator, with many interests. You adapt quickly and learn fast, but should avoid scattering your energy. Mercury is your lagna lord.', 'मिथुन लग्न आपको जिज्ञासु, हाज़िरजवाब और अच्छा वक्ता बनाता है; अनेक रुचियाँ। आप जल्दी ढलते और सीखते हैं, पर ऊर्जा बिखेरने से बचें। आपके लग्नेश बुध हैं।'),
  p('Karka lagna gives a caring, emotional and protective nature. Family, home and mother are central to your life; your intuition is strong, but moods can swing. The Moon is your lagna lord.', 'कर्क लग्न देखभाल करने वाला, भावुक और रक्षक स्वभाव देता है। परिवार, घर और माता आपके जीवन का केंद्र हैं; अंतर्ज्ञान प्रबल है, पर मनोदशा बदलती रहती है। आपके लग्नेश चंद्रमा हैं।'),
  p('Simha lagna makes you dignified, generous and confident, with a royal presence. You love respect and leadership; guard against pride and the need for constant praise. The Sun is your lagna lord.', 'सिंह लग्न आपको गरिमामय, उदार और आत्मविश्वासी बनाता है; राजसी व्यक्तित्व। आपको सम्मान और नेतृत्व प्रिय है; अहंकार और निरंतर प्रशंसा की चाह से बचें। आपके लग्नेश सूर्य हैं।'),
  p('Kanya lagna gives an analytical, practical and service-minded nature. You notice details, value health and order, and work hard; avoid over-criticism and worry. Mercury is your lagna lord.', 'कन्या लग्न विश्लेषक, व्यावहारिक और सेवाभावी स्वभाव देता है। आप बारीकियों पर ध्यान देते हैं, स्वास्थ्य व व्यवस्था को महत्व देते हैं और परिश्रमी हैं; अधिक आलोचना और चिंता से बचें। आपके लग्नेश बुध हैं।'),
  p('Tula lagna makes you balanced, charming and fair-minded, with a love of harmony, art and relationships. You are diplomatic, but indecision can hold you back. Venus is your lagna lord.', 'तुला लग्न आपको संतुलित, आकर्षक और न्यायप्रिय बनाता है; सामंजस्य, कला और संबंधों से प्रेम। आप कूटनीतिज्ञ हैं, पर अनिर्णय बाधा बन सकता है। आपके लग्नेश शुक्र हैं।'),
  p('Vrishchika lagna gives intensity, determination and deep emotions. You are secretive, perceptive and never give up; transform jealousy and anger into strength. Mars is your lagna lord.', 'वृश्चिक लग्न तीव्रता, दृढ़ संकल्प और गहरी भावनाएँ देता है। आप गोपनीय, पारखी और हार न मानने वाले हैं; ईर्ष्या और क्रोध को शक्ति में बदलें। आपके लग्नेश मंगल हैं।'),
  p('Dhanu lagna makes you optimistic, honest and fond of knowledge, travel and dharma. You are generous and philosophical; avoid being too blunt or careless with details. Jupiter is your lagna lord.', 'धनु लग्न आपको आशावादी, ईमानदार और ज्ञान, यात्रा व धर्म में रुचि रखने वाला बनाता है। आप उदार और दार्शनिक हैं; अधिक स्पष्टवादिता और लापरवाही से बचें। आपके लग्नेश गुरु हैं।'),
  p('Makara lagna gives a disciplined, ambitious and responsible nature. You work patiently towards long-term goals and success grows with age; remember to rest and express feelings. Saturn is your lagna lord.', 'मकर लग्न अनुशासित, महत्वाकांक्षी और ज़िम्मेदार स्वभाव देता है। आप दीर्घकालीन लक्ष्यों के लिए धैर्य से काम करते हैं और आयु के साथ सफलता बढ़ती है; विश्राम करना और भावनाएँ व्यक्त करना न भूलें। आपके लग्नेश शनि हैं।'),
  p('Kumbha lagna makes you independent, humanitarian and original in thinking. You value friendship and social causes; be careful not to seem detached. Saturn is your lagna lord.', 'कुंभ लग्न आपको स्वतंत्र, मानवतावादी और मौलिक विचारों वाला बनाता है। आप मित्रता और सामाजिक कार्यों को महत्व देते हैं; उदासीन न दिखें, इसका ध्यान रखें। आपके लग्नेश शनि हैं।'),
  p('Meena lagna gives a compassionate, imaginative and spiritual nature. You are kind, artistic and intuitive; set healthy boundaries and avoid escapism. Jupiter is your lagna lord.', 'मीन लग्न दयालु, कल्पनाशील और आध्यात्मिक स्वभाव देता है। आप करुणामय, कलाप्रेमी और अंतर्ज्ञानी हैं; स्वस्थ सीमाएँ बनाएँ और पलायनवाद से बचें। आपके लग्नेश गुरु हैं।'),
];

export const RASHI_PHAL = [
  p('With the Moon in Mesha, your mind is quick, enthusiastic and courageous. You react fast and get bored easily; physical activity keeps your mood bright.', 'मेष राशि में चंद्रमा होने से मन तेज़, उत्साही और साहसी है। आप जल्दी प्रतिक्रिया देते हैं और जल्दी ऊब जाते हैं; शारीरिक गतिविधि से मन प्रसन्न रहता है।'),
  p('The Moon is exalted in Vrishabha: your mind is calm, steady and content. You find peace in comfort, music and nature, and stay loyal in relationships.', 'वृषभ राशि में चंद्रमा उच्च का होता है: मन शांत, स्थिर और संतुष्ट रहता है। सुख-सुविधा, संगीत और प्रकृति में शांति मिलती है; संबंधों में वफ़ादार रहते हैं।'),
  p('With the Moon in Mithuna, your mind is curious, talkative and restless. You enjoy learning and conversation; writing your thoughts down brings calm.', 'मिथुन राशि में चंद्रमा होने से मन जिज्ञासु, बातूनी और चंचल है। सीखने और बातचीत में आनंद आता है; विचार लिखने से शांति मिलती है।'),
  p('The Moon is in its own sign in Karka: deeply caring, emotional and intuitive. Home and family give you security; protect yourself from taking on others’ worries.', 'कर्क राशि में चंद्रमा स्वराशि का होता है: गहरी देखभाल, भावुकता और अंतर्ज्ञान। घर-परिवार से सुरक्षा का भाव मिलता है; दूसरों की चिंताओं का बोझ न लें।'),
  p('With the Moon in Simha, your mind is proud, warm-hearted and generous. You need appreciation and like to shine; loyalty to loved ones is strong.', 'सिंह राशि में चंद्रमा होने से मन स्वाभिमानी, स्नेही और उदार है। आपको सराहना चाहिए और चमकना पसंद है; प्रियजनों के प्रति निष्ठा प्रबल।'),
  p('With the Moon in Kanya, your mind is analytical, practical and helpful. You notice flaws quickly, which can create worry; routine and service calm you.', 'कन्या राशि में चंद्रमा होने से मन विश्लेषक, व्यावहारिक और सहायक है। कमियाँ जल्दी दिखती हैं जिससे चिंता हो सकती है; दिनचर्या और सेवा से मन शांत होता है।'),
  p('With the Moon in Tula, your mind seeks balance, beauty and harmony. You dislike conflict and value partnership; decisions can take time.', 'तुला राशि में चंद्रमा होने से मन संतुलन, सौंदर्य और सामंजस्य चाहता है। विवाद पसंद नहीं और साझेदारी को महत्व देते हैं; निर्णय में समय लग सकता है।'),
  p('The Moon is debilitated in Vrishchika: emotions are intense and private, with strong intuition. Trust and letting go are life lessons; meditation and Shiva worship help.', 'वृश्चिक राशि में चंद्रमा नीच का होता है: भावनाएँ तीव्र और गोपनीय, अंतर्ज्ञान प्रबल। विश्वास करना और छोड़ देना जीवन की सीख है; ध्यान और शिव उपासना लाभदायक।'),
  p('With the Moon in Dhanu, your mind is optimistic, free-spirited and philosophical. Travel, learning and faith lift your mood.', 'धनु राशि में चंद्रमा होने से मन आशावादी, स्वतंत्र और दार्शनिक है। यात्रा, ज्ञान और आस्था से मन प्रसन्न रहता है।'),
  p('With the Moon in Makara, your mind is serious, responsible and practical. You may hide feelings behind duty; allow yourself rest and joy.', 'मकर राशि में चंद्रमा होने से मन गंभीर, ज़िम्मेदार और व्यावहारिक है। कर्तव्य के पीछे भावनाएँ छिपा सकते हैं; स्वयं को विश्राम और आनंद दें।'),
  p('With the Moon in Kumbha, your mind is independent, idealistic and friendly to all. You think differently and care about society; stay connected to your own feelings.', 'कुंभ राशि में चंद्रमा होने से मन स्वतंत्र, आदर्शवादी और सबका मित्र है। आप अलग सोचते हैं और समाज की चिंता करते हैं; अपनी भावनाओं से जुड़े रहें।'),
  p('With the Moon in Meena, your mind is gentle, compassionate and dreamy. You absorb the moods around you; prayer, music and quiet time restore you.', 'मीन राशि में चंद्रमा होने से मन कोमल, करुणामय और स्वप्निल है। आसपास का माहौल जल्दी ग्रहण करते हैं; प्रार्थना, संगीत और एकांत से ऊर्जा लौटती है।'),
];

// General results of each Mahadasha (or Antardasha) lord.
export const DASHA_PHAL = {
  sun: p('The Sun period brings focus on self-respect, career authority, government matters and father. Recognition is possible if you work with discipline; avoid ego conflicts and watch heart and eye health.', 'सूर्य की दशा आत्मसम्मान, करियर में अधिकार, सरकारी कार्य और पिता पर केंद्रित रहती है। अनुशासन से कार्य करें तो पहचान मिल सकती है; अहं के टकराव से बचें तथा हृदय और आँखों का ध्यान रखें।'),
  moon: p('The Moon period highlights emotions, mother, home, travel and public life. It can bring comfort, popularity and new beginnings, but also mood swings; keep the mind calm and routine steady.', 'चंद्रमा की दशा भावनाएँ, माता, घर, यात्रा और जनसंपर्क को प्रमुख बनाती है। यह सुख, लोकप्रियता और नई शुरुआत दे सकती है, पर मनोदशा में उतार-चढ़ाव भी; मन शांत और दिनचर्या नियमित रखें।'),
  mars: p('The Mars period brings energy, courage and action: property, siblings, competition and technical work come forward. Success comes through bold effort; control anger and drive carefully.', 'मंगल की दशा ऊर्जा, साहस और कर्मठता लाती है: भूमि, भाई-बहन, प्रतियोगिता और तकनीकी कार्य आगे आते हैं। साहसिक प्रयास से सफलता; क्रोध पर नियंत्रण रखें और वाहन सावधानी से चलाएँ।'),
  mercury: p('The Mercury period favours education, business, communication, writing and new skills. Intelligence is sharp and networking pays off; avoid overthinking and nervous stress.', 'बुध की दशा शिक्षा, व्यापार, संवाद, लेखन और नए कौशल के लिए अनुकूल है। बुद्धि तीव्र रहती है और संपर्कों से लाभ; अधिक सोचने और तनाव से बचें।'),
  jupiter: p('The Jupiter period is usually a time of growth, wisdom and blessings: education, marriage, children, wealth and spiritual progress. Guidance from gurus and elders brings success.', 'गुरु की दशा सामान्यतः उन्नति, ज्ञान और आशीर्वाद का समय होती है: शिक्षा, विवाह, संतान, धन और आध्यात्मिक प्रगति। गुरुजनों और बड़ों के मार्गदर्शन से सफलता।'),
  venus: p('The Venus period brings comfort, relationships, marriage, vehicles, arts and wealth. Life becomes more enjoyable; keep a balance and avoid over-indulgence.', 'शुक्र की दशा सुख-सुविधा, संबंध, विवाह, वाहन, कला और धन लाती है। जीवन अधिक आनंदमय होता है; संतुलन रखें और अति-भोग से बचें।'),
  saturn: p('The Saturn period teaches patience and discipline. Hard work brings lasting results in career and property, but delays and responsibilities increase; honesty and service bring Saturn’s blessings.', 'शनि की दशा धैर्य और अनुशासन सिखाती है। परिश्रम से करियर और संपत्ति में स्थायी परिणाम मिलते हैं, पर देरी और ज़िम्मेदारियाँ बढ़ती हैं; ईमानदारी और सेवा से शनि की कृपा मिलती है।'),
  rahu: p('The Rahu period brings sudden changes, ambition, foreign links and unconventional opportunities. Big gains are possible, but so is confusion; avoid shortcuts, intoxicants and blind risks.', 'राहु की दशा अचानक परिवर्तन, महत्वाकांक्षा, विदेश से संबंध और अपरंपरागत अवसर लाती है। बड़ा लाभ संभव है, पर भ्रम भी; शॉर्टकट, नशे और अंधे जोखिम से बचें।'),
  ketu: p('The Ketu period turns the mind inward: spirituality, detachment, research and sudden endings that make space for growth. Stay grounded, look after health and seek a guru’s guidance.', 'केतु की दशा मन को भीतर की ओर मोड़ती है: अध्यात्म, विरक्ति, शोध और ऐसे अचानक अंत जो विकास का मार्ग बनाते हैं। स्थिर रहें, स्वास्थ्य का ध्यान रखें और गुरु का मार्गदर्शन लें।'),
};
